import { Hct, SchemeTonalSpot, argbFromHex, hexFromArgb } from '@material/material-color-utilities';
import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const seeds = { green: '#91c4ae', purple: '#6750a4', blue: '#386aaf', rose: '#984061' };
const roles = { primary: 'primary', 'on-primary': 'onPrimary', 'primary-container': 'primaryContainer', 'on-primary-container': 'onPrimaryContainer', info: 'secondary', 'on-info': 'onSecondary', 'info-container': 'secondaryContainer', 'on-info-container': 'onSecondaryContainer' };
const presets = Object.fromEntries(Object.entries(seeds).map(([id, seed]) => {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(seed)), true, 0);
  return [id, Object.fromEntries(Object.entries(roles).map(([role, key]) => [role, hexFromArgb(scheme[key])]))];
}));
export const output = `// Generated by scripts/generate-themes.mjs using Google Material Color Utilities 0.3.0.\n// Tonal Spot, dark, standard contrast; project-selected source colors.\nexport const themePresets = ${JSON.stringify(presets, null, 2)};\n`;

export function verifyThemePresets(source) {
  if (source.replace(/\r\n/g, '\n') !== output) throw new Error('Theme presets are out of date');
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) {
  const path = new URL('../public/theme-presets.js', import.meta.url);
  if (process.argv.includes('--check')) verifyThemePresets(await readFile(path, 'utf8'));
  else await writeFile(path, output);
}
