import { Hct, SchemeTonalSpot, argbFromHex, hexFromArgb } from '@material/material-color-utilities';
import { readFile, writeFile } from 'node:fs/promises';

const seeds = { green: '#91c4ae', purple: '#6750a4', blue: '#386aaf', rose: '#984061' };
const roles = { primary: 'primary', 'on-primary': 'onPrimary', 'primary-container': 'primaryContainer', 'on-primary-container': 'onPrimaryContainer', info: 'secondary', 'on-info': 'onSecondary', 'info-container': 'secondaryContainer', 'on-info-container': 'onSecondaryContainer' };
const presets = Object.fromEntries(Object.entries(seeds).map(([id, seed]) => {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(seed)), true, 0);
  return [id, Object.fromEntries(Object.entries(roles).map(([role, key]) => [role, hexFromArgb(scheme[key])]))];
}));
const output = `// Generated by scripts/generate-themes.mjs using Google Material Color Utilities 0.3.0.\n// Tonal Spot, dark, standard contrast; project-selected source colors.\nexport const themePresets = ${JSON.stringify(presets, null, 2)};\n`;
const path = new URL('../public/theme-presets.js', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(path, 'utf8') !== output) throw new Error('Theme presets are out of date');
} else await writeFile(path, output);
